### ISSUE TITLE
how do u call a function?

### ISSUE THREAD

**Issue by gregmcewanmarriott** [JoeSz/Exopite-Frontend-Notifications#1]
Installed and activated your very cool plugin on a site  and added the two  functions in my themes function file .... i tried calling the functions with

my_ajax_callback_function ('Test logged_in');

but i get no notification.... how do i call the functions?

**Comment by JoeSz** [comment]
Sorry for the late answer, I didn't see your message.
I make a mistake in the readme file. The hook name (if not with AJAX): "efn_messages"
So can you use it:

```php
function my_notifications( $messages ) {

    $my_messages = array(
        array(
            'delay' => false,
            'title' => 'No delay',
            'msg' => 'Test logged_in',
        ),
        // ...
    );

    $messages = array_merge( $messages, $my_messages );

    return $messages;
}
add_filter( 'efn_messages', 'my_notifications' );
```
